### ISSUE TITLE
Add-on deletes itself on reboot

### ISSUE THREAD

**Issue by bluet-it** [flatsiedatsie/power-settings#2]
When rebooting, the menu and the add-on disappear from the list. Both rebooting from the menu and through SSH. 
Workaround: after rebooting, reinstall from add-on manager, sign-out and in.

**Comment by flatsiedatsie** [comment]
That sounds very strange. Can you see anything in the internal logs that relates to this?

**Comment by v-turcsanyi** [comment]
in /var/log/syslog
`Feb  7 14:22:40 gateway run-app.sh[392]: #033[31m2020-02-07 14:22:40.026 ERROR  : Failed to load add-on power-settings: Error: Checksum failed for file /home/pi/.mozilla-iot/addons/power-settings/pkg/__pycache__/power_settings.cpython-37.pyc in add-on power-settings#033[39m`

**Comment by flatsiedatsie** [comment]
That's very odd. Thanks for reporting.

**Comment by jherb-oly3x** [comment]
I see the same thing:

2020-02-14 07:05:55.808 ERROR  : Failed to load add-on power-settings: Error: Checksum failed for file /home/pi/.mozilla-iot/addons/power-settings/pkg/__pycache__/power_settings.cpython-37.pyc in add-on power-settings
    at find.fileSync.forEach (/home/pi/mozilla-iot/gateway/build/webpack:/src/addon-utils.js:384:1)
    at Array.forEach (<anonymous>)
    at loadManifestJson (/home/pi/mozilla-iot/gateway/build/webpack:/src/addon-utils.js:366:1)
    at Object.loadManifest (/home/pi/mozilla-iot/gateway/build/webpack:/src/addon-utils.js:472:1)
    at AddonManager.loadAddon (/home/pi/mozilla-iot/gateway/build/webpack:/src/addon-manager.js:621:1)
    at fs.readdir (/home/pi/mozilla-iot/gateway/build/webpack:/src/addon-manager.js:794:1)
    at FSReqWrap.oncomplete (fs.js:135:15)

**Comment by flatsiedatsie** [comment]
The issue should be fixed. Please let me know if you still experience issues.
