### ISSUE TITLE
Compatibility with Gateway v0.11.0

### ISSUE THREAD

**Issue by stefanreimers** [flatsiedatsie/power-settings#3]
After updating the Mozilla Gateway to the latest version v0.11.0 the power-settings addon repeatedly breaks and restarts. Some excerpt from my logs:

```
2020-02-23 10:47:46.933 INFO   : Plugin: power-settings died, code = 1 restarting after 30000
2020-02-23 10:48:18.136 INFO   : power-settings: Import APIHandler and APIResponse from gateway_addon failed. Use at least WebThings Gateway version 0.10
2020-02-23 10:48:18.139 ERROR  : power-settings: Traceback (most recent call last):
2020-02-23 10:48:18.141 ERROR  : power-settings:   File "/home/pi/.mozilla-iot/addons/power-settings/main.py", line 13, in <module>
2020-02-23 10:48:18.143 ERROR  : power-settings:     from pkg.power_settings import PowerSettingsAPIHandler  # noqa
2020-02-23 10:48:18.145 ERROR  : power-settings:   File "/home/pi/.mozilla-iot/addons/power-settings/pkg/power_settings.py", line 21, in <module>
2020-02-23 10:48:18.147 ERROR  : power-settings:     class PowerSettingsAPIHandler(APIHandler):
2020-02-23 10:48:18.148 ERROR  : power-settings: NameError: name 'APIHandler' is not defined
2020-02-23 10:48:18.280 INFO   : Plugin: power-settings died, code = 1 restarting after 30000
2020-02-23 10:48:30.487 INFO   : Killing power-settings plugin.
```

My Gateway is running on a Raspberry Pi 3. For now I disabled the plugin.

**Comment by flatsiedatsie** [comment]
Thanks, I'll look into it.

**Comment by wrldtvlr** [comment]
I tried to add this device on my Pi 4 running Gateway v0.12.0, but it doesn't seem to even start up. Nothing in the log file. Have disabled.

**Comment by flatsiedatsie** [comment]
@stefanreimers it seems something was wrong with your Gateway. The `gateway_addon` should be a default package which is part of the Gateway. Did you perhaps build the software yourself? Then this can be omitted.

@wrldtvlr If there is abslutely nothing in the log, then it wasn't even loaded. You should see _something_. Are you running this on a Rasbperry Pi with the official image, or some other construction?

**Comment by wrldtvlr** [comment]
@flatsiedatsie  OK - my problem was that I was looking at the Android menu and hadn't completely refreshed the page after enabling the add-on. It does show up now as well as with a PC browser window.

**Comment by flatsiedatsie** [comment]
Ah, thanks for the explanation. This is actually something that will be 'fixed' in the next version of the gateway.
