### ISSUE TITLE
PowerSettings crash

### ISSUE THREAD

**Issue by chas-iot** [flatsiedatsie/power-settings#7]
I'm seeing these messages repeating in the gateway logs.
Raspberry Pi
Gateway 1.0
````
2020-12-11 00:49:41.952 INFO   : Plugin: power-settings died, code = 1 restarting after 30000
2020-12-11 00:50:12.509 ERROR  : power-settings: Traceback (most recent call last):
2020-12-11 00:50:12.511 ERROR  : power-settings:   File "/home/pi/.webthings/addons/power-settings/main.py", line 13, in <module>
2020-12-11 00:50:12.513 ERROR  : power-settings:     from pkg.power_settings import PowerSettingsAPIHandler  # noqa
2020-12-11 00:50:12.515 ERROR  : power-settings:   File "/home/pi/.webthings/addons/power-settings/pkg/power_settings.py", line 222
2020-12-11 00:50:12.516 ERROR  : power-settings:     print("Power settings: s rebooting gateway").
2020-12-11 00:50:12.518 ERROR  : power-settings:                                                 ^
2020-12-11 00:50:12.519 ERROR  : power-settings: SyntaxError: invalid syntax
2020-12-11 00:50:12.582 INFO   : Plugin: power-settings died, code = 1 restarting after 30000
2020-12-11 00:50:43.123 ERROR  : power-settings: Traceback (most recent call last):
2020-12-11 00:50:43.125 ERROR  : power-settings:   File "/home/pi/.webthings/addons/power-settings/main.py", line 13, in <module>
2020-12-11 00:50:43.127 ERROR  : power-settings:     from pkg.power_settings import PowerSettingsAPIHandler  # noqa
2020-12-11 00:50:43.128 ERROR  : power-settings:   File "/home/pi/.webthings/addons/power-settings/pkg/power_settings.py", line 222
2020-12-11 00:50:43.130 ERROR  : power-settings:     print("Power settings: s rebooting gateway").
2020-12-11 00:50:43.131 ERROR  : power-settings:                                                 ^
2020-12-11 00:50:43.133 ERROR  : power-settings: SyntaxError: invalid syntax
````

**Comment by flatsiedatsie** [comment]
Thanks. I've just fixed it.
