### ISSUE TITLE
error message on statup

### ISSUE THREAD

**Issue by chas-iot** [flatsiedatsie/power-settings#8]
new reproducable message on starting extension
````
2020-12-15 03:48:05.597 INFO   : Loading add-on: power-settings
2020-12-15 03:48:06.147 ERROR  : power-settings: Traceback (most recent call last):
2020-12-15 03:48:06.149 ERROR  : power-settings:   File "/home/pi/.webthings/addons/power-settings/main.py", line 13, in <module>
2020-12-15 03:48:06.151 ERROR  : power-settings:     from pkg.power_settings import PowerSettingsAPIHandler  # noqa
2020-12-15 03:48:06.153 ERROR  : power-settings:   File "/home/pi/.webthings/addons/power-settings/pkg/power_settings.py", line 6, in <module>
2020-12-15 03:48:06.154 ERROR  : power-settings:     sys.path.append(path.join(path.dirname(path.abspath(__file__)), 'lib'))
2020-12-15 03:48:06.156 ERROR  : power-settings: NameError: name 'path' is not defined

**Comment by flatsiedatsie** [comment]
Thanks again. Should be fixed. This time I did some proper testing.
